CREATE TABLE IF NOT EXISTS Players (
    SteamID32 INTEGER UNSIGNED NOT NULL,
    Alias VARCHAR(32),
    Country VARCHAR(45),
    IP VARCHAR(15),
    Cheater TINYINT UNSIGNED NOT NULL DEFAULT '0',
    LastPlayed TIMESTAMP NULL DEFAULT NULL,
    Created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_Player PRIMARY KEY (SteamID32)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS Maps (
    MapID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    Name VARCHAR(32) NOT NULL UNIQUE,
    LastPlayed TIMESTAMP NULL DEFAULT NULL,
    Created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_Maps PRIMARY KEY (MapID)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS MapCourses (
    MapCourseID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    MapID INTEGER UNSIGNED NOT NULL,
    Course INTEGER UNSIGNED NOT NULL,
    Created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_MapCourses PRIMARY KEY (MapCourseID),
    CONSTRAINT UQ_MapCourses_MapIDCourse UNIQUE (MapID, Course),
    CONSTRAINT FK_MapCourses_MapID FOREIGN KEY (MapID) REFERENCES Maps(MapID)
    ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS Times (
    TimeID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    SteamID32 INTEGER UNSIGNED NOT NULL,
    MapCourseID INTEGER UNSIGNED NOT NULL,
    Mode TINYINT UNSIGNED NOT NULL,
    Style TINYINT UNSIGNED NOT NULL,
    RunTime INTEGER UNSIGNED NOT NULL,
    Teleports SMALLINT UNSIGNED NOT NULL,
    Created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_Times PRIMARY KEY (TimeID),
    CONSTRAINT FK_Times_SteamID32 FOREIGN KEY (SteamID32) REFERENCES Players(SteamID32)
    ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT FK_Times_MapCourseID FOREIGN KEY (MapCourseID) REFERENCES MapCourses(MapCourseID)
    ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS Jumpstats (
    JumpID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    SteamID32 INTEGER UNSIGNED NOT NULL,
    JumpType TINYINT UNSIGNED NOT NULL,
    Mode TINYINT UNSIGNED NOT NULL,
    Distance INTEGER UNSIGNED NOT NULL,
    IsBlockJump TINYINT UNSIGNED NOT NULL,
    Block SMALLINT UNSIGNED NOT NULL,
    Strafes INTEGER UNSIGNED NOT NULL,
    Sync INTEGER UNSIGNED NOT NULL,
    Pre INTEGER UNSIGNED NOT NULL,
    Max INTEGER UNSIGNED NOT NULL,
    Airtime INTEGER UNSIGNED NOT NULL,
    Created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_Jumpstats PRIMARY KEY (JumpID),
    CONSTRAINT FK_Jumpstats_SteamID32 FOREIGN KEY (SteamID32) REFERENCES Players(SteamID32)
    ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS VBPosition (
    SteamID32 INTEGER UNSIGNED NOT NULL,
    MapID INTEGER UNSIGNED NOT NULL,
    X REAL NOT NULL,
    Y REAL NOT NULL,
    Z REAL NOT NULL,
    Course INTEGER NOT NULL,
    IsStart INTEGER NOT NULL,
    CONSTRAINT PK_VBPosition PRIMARY KEY (SteamID32, MapID, IsStart),
    CONSTRAINT FK_VBPosition_SteamID32 FOREIGN KEY (SteamID32) REFERENCES Players(SteamID32),
    CONSTRAINT FK_VBPosition_MapID FOREIGN KEY (MapID) REFERENCES Maps(MapID)
    ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS StartPosition (
    SteamID32 INTEGER UNSIGNED NOT NULL,
    MapID INTEGER UNSIGNED NOT NULL,
    X REAL NOT NULL,
    Y REAL NOT NULL,
    Z REAL NOT NULL,
    Angle0 REAL NOT NULL,
    Angle1 REAL NOT NULL,
    CONSTRAINT PK_StartPosition PRIMARY KEY (SteamID32, MapID),
    CONSTRAINT FK_StartPosition_SteamID32 FOREIGN KEY (SteamID32) REFERENCES Players(SteamID32),
    CONSTRAINT FK_StartPosition_MapID FOREIGN KEY (MapID) REFERENCES Maps(MapID)
    ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS Replays (
    ReplayID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    ReplayType TINYINT UNSIGNED NOT NULL,
    TimeID INTEGER UNSIGNED NULL,
    JumpID INTEGER UNSIGNED NULL,
    SteamID32 INTEGER UNSIGNED NOT NULL,
    ObjectKey VARCHAR(191) NOT NULL,
    FileSize INTEGER UNSIGNED NOT NULL,
    InStore TINYINT UNSIGNED NOT NULL DEFAULT 0,
    MapName VARCHAR(64) NOT NULL DEFAULT '',
    Code VARCHAR(8) NOT NULL,
    Created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_Replays PRIMARY KEY (ReplayID),
    CONSTRAINT UQ_Replays_ObjectKey UNIQUE (ObjectKey),
    CONSTRAINT UQ_Replays_Code UNIQUE (Code),
    INDEX IX_Replays_TimeID (TimeID),
    INDEX IX_Replays_JumpID (JumpID),
    INDEX IX_Replays_SteamID32 (SteamID32),
    CONSTRAINT FK_Replays_TimeID FOREIGN KEY (TimeID) REFERENCES Times(TimeID)
    ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT FK_Replays_JumpID FOREIGN KEY (JumpID) REFERENCES Jumpstats(JumpID)
    ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB;
